version: "3.7"
services:
  redis:
    container_name: ppln-form-redis
    image: redis:alpine
    volumes:
      - ppln-form-redis:/data
    ports:
      - "6379:6379"
  redis-commander:
    container_name: ppln-form-redis-commander
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
  mailcatcher:
    image: dockage/mailcatcher:0.8.2
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  ppln-form-redis:
